### PR TITLE
Hashi-update

### PR DESCRIPTION
**Pull request by ChrisMcKee**
Packer + TF12 update

### CODE REVIEW

**Comment by osterman** [comment]
test

**Comment by Nuru** [comment]
@ChrisMcKee Thank you for your contribution. Due to some CI/CD integration issues it was easier for me to include your changes in #226 then to merge this PR directly to master. I hope you don't mind. The end result is the packages you upgraded are now available.

**Comment by ChrisMcKee** [comment]
Wont someone think of my commit graph 😱 
Nah, kidding, all good. 😉

**Pull request closed without merging**
