### PR TITLE
[helm, helmfile] update to latest release

### PR DESCRIPTION
**Pull request by rverma-nikiai**
## what
* Update `helm` to latest release
* Update `helmfile` to latest release

## why
* Maintenance

### CODE REVIEW

**Comment by rverma-nikiai** [comment]
I believe automation would be very helpful in these kinds of scenario. A pull request merge should trigger an update with the readme. If you are planning to integrated dependabot it might make sense and simplify the depandabot workflow. Nevermind I update readme for now :)

**Comment by osterman** [comment]
@rverma-nikiai I 💯 agree... just no shortage of these kinds of projects. We currently don't have the ability to modify a PR using a bot, so the scope is quite large. Additionally, the dependabot PRs are managed by a thirdparty. And while that bot is open source, it's nothing we've setup previously.

**Comment by rverma-nikiai** [comment]
Modifying a PR is not the approach, it would be that it's merged you
regenerate docs and add an extra commit to update Readme. You will need to
add an github key to travis though for this.

**Comment by rverma-nikiai** [comment]
How a new docker image would be generated, is it on a weekly schedule?

**Pull request merged**
