### PR TITLE
[sops] Update to 3.2.0

### PR DESCRIPTION
**Pull request by ChrisMcKee**
Sops 3.1 to 3.2.0

### CODE REVIEW

**Comment by osterman** [comment]
Just one thing... The `README.md` is generated automatically.

Please rebuild the `README.md` by running the following commands:
```
make init
make readme/deps
make readme
```

There might be a lot of changes in the `README.md` as a result. That's okay! 

Sorry for the inconvenience!

**Comment by ChrisMcKee** [comment]
```
make readme/deps
Installing packages 0.84.0...
Cloning into '/i/cloudposse_packages/build-harness/vendor/packages'...
remote: Enumerating objects: 284, done.
remote: Counting objects: 100% (284/284), done.
remote: Compressing objects: 100% (141/141), done.
remote: Total 284 (delta 49), reused 241 (delta 42), pack-reused 0
Receiving objects: 100% (284/284), 51.50 KiB | 712.00 KiB/s, done.
Resolving deltas: 100% (49/49), done.
make[1]: Entering directory '/i/cloudposse_packages/build-harness/vendor/packages/install'
make[2]: Entering directory '/i/cloudposse_packages/build-harness/vendor/packages/vendor/gomplate'
curl --retry 3 --retry-delay 5 --fail -sSL -o /usr/local/bin/gomplate https://github.com/hairyhenderson/gomplate/releases/download/v3.1.0/gomplate_linux-amd64-slim && chmod +x /usr/local/bin/gomplate
curl: (23) Failed writing body (0 != 8556)
Makefile:10: recipe for target 'install' failed
make[2]: *** [install] Error 23
make[2]: Leaving directory '/i/cloudposse_packages/build-harness/vendor/packages/vendor/gomplate'
Makefile:9: recipe for target 'gomplate' failed
make[1]: *** [gomplate] Error 2
make[1]: Leaving directory '/i/cloudposse_packages/build-harness/vendor/packages/install'
/i/cloudposse_packages/build-harness/modules/packages/Makefile:24: recipe for target 'packages/install/gomplate' failed
make: *** [packages/install/gomplate] Error 2
```

**Comment by osterman** [comment]
@ChrisMcKee it's trying to write to `/usr/local/bin` and doesn't have permission. You can rerun with `sudo` or change the `INSTALL_PATH`

**Comment by ChrisMcKee** [comment]
This is a weird productivity hack for a markdown file 😅

**Comment by osterman** [comment]
> This is a weird productivity hack for a markdown file 

It's the only way we can maintain 300+ repos with some semblance of sanity and consistency. For example, because we do this, we can do useful things like validate that the `README.md` was updated.

**Comment by ChrisMcKee** [comment]
sorted

**Comment by ChrisMcKee** [comment]
force pushed as the "update branch" crap in github merged the change in rather than rebased

**Pull request merged**
