### PR TITLE
Update kubectl-1.17 to 1.17.15

### PR DESCRIPTION
**Pull request by cloudpossebot**
## what

This is an auto-generated PR that updates the kubectl-1.17 package version.

| Meta              | Details                                      |
|:------------------|:---------------------------------------------|
| **Package Name**  | `kubectl-1.17`   |
| **Vendor**        | [kubernetes](https://github.com/kubernetes/) |
| **Version**       | 1.17.15  |
| **License**       | APACHE-2.0  |
| **Repo**          | https://github.com/kubernetes/kubernetes |
| **Arch**          | x86_64             |
| **OS**            | linux               |
| **Download URL**  | https://storage.googleapis.com/kubernetes-release/release/v1.17.15/bin/linux/amd64/kubectl     |

## why

Publish the latest release of `kubectl-1.17` to our package repository.

### CODE REVIEW

**Comment by Nuru** [comment]
@osterman Kind of cool. Our smoke test caught that the `kubectl` released as version 1.17.15 is identifying itself as v1.17.16-rc.0, which is why this package is failing

**Comment by osterman** [comment]
That's great!

**Comment by Nuru** [comment]
Hold for https://github.com/kubernetes/kubernetes/issues/97178

**Comment by Nuru** [comment]
Apparently 1.17.15 release was not fixed, they just moved on to 1.17.16. Closing this PR because there is no valid 1.17.15 kubectl to package.

**Pull request closed without merging**
