### PR TITLE
Helm - bump version

### PR DESCRIPTION
**Pull request by alebabai**
## what
* use helm 2.9.1

## why
* #12

### CODE REVIEW

**Comment by alebabai** [comment]
@osterman maybe you know, why the build failed for this.

> caused by Error: (HTTP code 500) server error - invalid tag form

**Comment by osterman** [comment]
@alebabai ok, this is a bug in the `build-harness` target for `semver`. It does not handle the branch name normalization for `0.2.2-feature/upgrade-helm.sha.4a69d0e`. I'll submit a fix.

**Comment by osterman** [comment]
https://github.com/cloudposse/build-harness/pull/68

**Comment by osterman** [comment]
@alebabai upgrade to https://github.com/cloudposse/build-harness/releases/tag/0.6.4

**Pull request merged**
