### PR TITLE
[helm,helmfile,kubectx,kubens,aws-iam-authenticator]updated 

### PR DESCRIPTION
**Pull request by rverma-nikiai**
updated [helm,helmfile,kubectx,kubens,aws-iam-authenticator]

### CODE REVIEW

**Comment by rverma-nikiai** [comment]
@osterman `curl --retry 3 --retry-delay 5 --fail -sSL -o - https://github.com/alecthomas/gometalinter/releases/download/v2.0.11/gometalinter-2.0.11-linux-amd64.tar.gz | tar -zx -C`  hangs for quite some time. I also noticed that the repo is deprecated.

**Comment by osterman** [comment]
@rverma-nikiai thanks for taking a shot at upgrading. 

Unfortunately, looks like more problems with `aws-iam-authenticator` on alpine 3.7.

I am thinking maybe we end support for it.

image


image

**Comment by rverma-nikiai** [comment]
Since we are using debian base it work fine for us :)

**Comment by osterman** [comment]
@rverma-nikiai I didn't get to this today, but tomorrow more likely.

**Pull request closed without merging**
